/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/accounts/{account_id}": {
    /**
     * Account Snapshot
     * @description Perform account_snapshot.
     */
    get: operations["account_snapshot_accounts__account_id__get"];
  };
  "/backtests": {
    /**
     * List Backtests
     * @description List recent backtest runs from persisted summaries.
     */
    get: operations["list_backtests_backtests_get"];
    /**
     * Submit Backtest
     * @description Submit a backtest request through the backtest application service.
     */
    post: operations["submit_backtest_backtests_post"];
  };
  "/backtests/strategy-options": {
    /**
     * List Backtest Strategy Options
     * @description List runnable backtest strategy options from configured backtest files.
     */
    get: operations["list_backtest_strategy_options_backtests_strategy_options_get"];
  };
  "/health": {
    /**
     * Health
     * @description Perform health.
     */
    get: operations["health_health_get"];
  };
  "/operations/kill-switches": {
    /**
     * Activate Kill Switch
     * @description Activate or refresh a kill-switch for a runtime scope.
     */
    post: operations["activate_kill_switch_operations_kill_switches_post"];
  };
  "/operations/kill-switches/deactivate": {
    /**
     * Deactivate Kill Switch
     * @description Deactivate or refresh an inactive kill-switch state for a runtime scope.
     */
    post: operations["deactivate_kill_switch_operations_kill_switches_deactivate_post"];
  };
  "/operations/operator-status": {
    /**
     * Operator Status
     * @description Return application-owned operator dashboard status.
     */
    get: operations["operator_status_operations_operator_status_get"];
  };
  "/operations/runtime/enter-observation": {
    /**
     * Enter Observation
     * @description Enter observation mode while keeping runtime visibility.
     */
    post: operations["enter_observation_operations_runtime_enter_observation_post"];
  };
  "/operations/runtime/exit-observation": {
    /**
     * Exit Observation
     * @description Exit observation mode after operator approval.
     */
    post: operations["exit_observation_operations_runtime_exit_observation_post"];
  };
  "/operations/runtime/pause": {
    /**
     * Pause Runtime
     * @description Pause runtime execution for all strategies and data actors.
     */
    post: operations["pause_runtime_operations_runtime_pause_post"];
  };
  "/operations/runtime/reconcile": {
    /**
     * Reconcile Runtime
     * @description Request runtime reconciliation through the operational command boundary.
     */
    post: operations["reconcile_runtime_operations_runtime_reconcile_post"];
  };
  "/operations/runtime/resume": {
    /**
     * Resume Runtime
     * @description Resume runtime execution after an operator pause.
     */
    post: operations["resume_runtime_operations_runtime_resume_post"];
  };
  "/operations/runtime/snapshot": {
    /**
     * Snapshot Runtime
     * @description Request a runtime snapshot through the operational command boundary.
     */
    post: operations["snapshot_runtime_operations_runtime_snapshot_post"];
  };
  "/operations/runtime/start": {
    /**
     * Start Runtime
     * @description Start runtime processing.
     */
    post: operations["start_runtime_operations_runtime_start_post"];
  };
  "/operations/runtime/stop": {
    /**
     * Stop Runtime
     * @description Stop runtime processing.
     */
    post: operations["stop_runtime_operations_runtime_stop_post"];
  };
  "/orders/{order_id}": {
    /**
     * Order Status
     * @description Perform order_status.
     */
    get: operations["order_status_orders__order_id__get"];
  };
  "/strategies": {
    /**
     * List Strategies
     * @description Perform list_strategies.
     */
    get: operations["list_strategies_strategies_get"];
  };
  "/strategies/{strategy_id}/start": {
    /**
     * Start Strategy
     * @description Perform start_strategy.
     */
    post: operations["start_strategy_strategies__strategy_id__start_post"];
  };
  "/strategies/{strategy_id}/stop": {
    /**
     * Stop Strategy
     * @description Perform stop_strategy.
     */
    post: operations["stop_strategy_strategies__strategy_id__stop_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AccountSnapshotSchema
     * @description Account snapshot response schema.
     */
    AccountSnapshotSchema: {
      /** Account Id */
      account_id: string;
      /** Cash */
      cash: {
        [key: string]: string;
      };
    };
    /**
     * BacktestRequestSchema
     * @description HTTP request for submitting a backtest.
     */
    BacktestRequestSchema: {
      /** Config Path */
      config_path: string;
    };
    /**
     * BacktestRunResultSchema
     * @description HTTP response for a submitted research backtest run.
     */
    BacktestRunResultSchema: {
      /** Artifact Hashes */
      artifact_hashes: {
        [key: string]: string;
      };
      /** Equity Curve Path */
      equity_curve_path: string;
      /** Fills Path */
      fills_path: string;
      /** Manifest Path */
      manifest_path: string;
      /** Metrics */
      metrics: {
        [key: string]: unknown;
      };
      /** Orders Path */
      orders_path: string;
      /** Run Id */
      run_id: string;
    };
    /**
     * BacktestRunSchema
     * @description HTTP response for a listed backtest summary.
     */
    BacktestRunSchema: {
      /** Config Path */
      config_path: string;
      /** Run Id */
      run_id: string;
      /** Status */
      status: string;
    };
    /**
     * BacktestStrategyOptionSchema
     * @description HTTP response for a runnable backtest strategy option.
     */
    BacktestStrategyOptionSchema: {
      /** Config Path */
      config_path: string;
      /** Label */
      label: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * KillSwitchCommandSchema
     * @description Kill-switch mutation command.
     */
    KillSwitchCommandSchema: {
      /** Reason */
      reason: string;
      scope: components["schemas"]["KillSwitchScopeSchema"];
      /** Scope Id */
      scope_id?: string | null;
    };
    /**
     * KillSwitchResponseSchema
     * @description Kill-switch current state response.
     */
    KillSwitchResponseSchema: {
      /** Active */
      active: boolean;
      /** Reason */
      reason: string;
      /** Scope */
      scope: string;
      /** Scope Id */
      scope_id: string | null;
    };
    /**
     * KillSwitchScopeSchema
     * @description Kill-switch scoping model.
     * @enum {string}
     */
    KillSwitchScopeSchema: "global" | "account" | "strategy" | "instrument";
    /**
     * OrderStatusSchema
     * @description Order status response schema.
     */
    OrderStatusSchema: {
      /** Order Id */
      order_id: string;
      /** Status */
      status: string;
    };
    /**
     * RuntimeCommandResponseSchema
     * @description Payload for runtime pause/resume commands.
     */
    RuntimeCommandResponseSchema: {
      /** State */
      state: string;
    };
    /**
     * RuntimeCommandResultResponseSchema
     * @description Payload for auditable runtime command results.
     */
    RuntimeCommandResultResponseSchema: {
      /** Command Id */
      command_id: string;
      /** Evidence */
      evidence: {
        [key: string]: unknown;
      };
      /** Failure Reason */
      failure_reason?: string | null;
      /** Idempotency Key */
      idempotency_key: string;
      /** Reason Code */
      reason_code?: string | null;
      /** Status */
      status: string;
    };
    /**
     * StrategyStatusSchema
     * @description Strategy status response schema.
     */
    StrategyStatusSchema: {
      /** Status */
      status: string;
      /** Strategy Id */
      strategy_id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Account Snapshot
   * @description Perform account_snapshot.
   */
  account_snapshot_accounts__account_id__get: {
    parameters: {
      path: {
        account_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountSnapshotSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Backtests
   * @description List recent backtest runs from persisted summaries.
   */
  list_backtests_backtests_get: {
    parameters: {
      query?: {
        limit?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BacktestRunSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Submit Backtest
   * @description Submit a backtest request through the backtest application service.
   */
  submit_backtest_backtests_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BacktestRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BacktestRunResultSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Backtest Strategy Options
   * @description List runnable backtest strategy options from configured backtest files.
   */
  list_backtest_strategy_options_backtests_strategy_options_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BacktestStrategyOptionSchema"][];
        };
      };
    };
  };
  /**
   * Health
   * @description Perform health.
   */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * Activate Kill Switch
   * @description Activate or refresh a kill-switch for a runtime scope.
   */
  activate_kill_switch_operations_kill_switches_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KillSwitchCommandSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KillSwitchResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Deactivate Kill Switch
   * @description Deactivate or refresh an inactive kill-switch state for a runtime scope.
   */
  deactivate_kill_switch_operations_kill_switches_deactivate_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
        "X-QTS-Authorization-Scope"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KillSwitchCommandSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KillSwitchResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Operator Status
   * @description Return application-owned operator dashboard status.
   */
  operator_status_operations_operator_status_get: {
    parameters: {
      header?: {
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Enter Observation
   * @description Enter observation mode while keeping runtime visibility.
   */
  enter_observation_operations_runtime_enter_observation_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Exit Observation
   * @description Exit observation mode after operator approval.
   */
  exit_observation_operations_runtime_exit_observation_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Pause Runtime
   * @description Pause runtime execution for all strategies and data actors.
   */
  pause_runtime_operations_runtime_pause_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Reconcile Runtime
   * @description Request runtime reconciliation through the operational command boundary.
   */
  reconcile_runtime_operations_runtime_reconcile_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResultResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Resume Runtime
   * @description Resume runtime execution after an operator pause.
   */
  resume_runtime_operations_runtime_resume_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Snapshot Runtime
   * @description Request a runtime snapshot through the operational command boundary.
   */
  snapshot_runtime_operations_runtime_snapshot_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResultResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Start Runtime
   * @description Start runtime processing.
   */
  start_runtime_operations_runtime_start_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Stop Runtime
   * @description Stop runtime processing.
   */
  stop_runtime_operations_runtime_stop_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
        "X-QTS-Operator"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RuntimeCommandResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Order Status
   * @description Perform order_status.
   */
  order_status_orders__order_id__get: {
    parameters: {
      path: {
        order_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrderStatusSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Strategies
   * @description Perform list_strategies.
   */
  list_strategies_strategies_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StrategyStatusSchema"][];
        };
      };
    };
  };
  /**
   * Start Strategy
   * @description Perform start_strategy.
   */
  start_strategy_strategies__strategy_id__start_post: {
    parameters: {
      path: {
        strategy_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StrategyStatusSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Stop Strategy
   * @description Perform stop_strategy.
   */
  stop_strategy_strategies__strategy_id__stop_post: {
    parameters: {
      path: {
        strategy_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StrategyStatusSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
